include:
  - README.md
theme: jekyll-theme-cayman
title: $\color{lightgreen}{\large\textbf{E-Co}}$‎​mpare
description: $\color{lightgreen}{\large\textbf{E-Co}}$‎​mpare is a tool to compare the energy consumption of different versions of the same software.