name: 'Measure Energy'
description: 'Measures energy in the background of your unit tests'
inputs:
  run:
    description: 'Which command to measure the power usage of. Presumed to be unit tests'
    required: true
  GITHUB_TOKEN:
    description: 'The secret github token so the tool can place comments'
    required: true
  count:
    description: 'How many times to run the command'
    required: false
    default: '1'
runs:
  using: 'node20'
  main: 'dist/index.js'
