on:
  workflow_dispatch:
jobs:
  measure-energy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: sudo chgrp -R msr /dev/cpu/*/msr;
      - run: sudo chmod g+r /dev/cpu/*/msr;
      - run: cargo build -r;
      - run: sudo setcap cap_sys_rawio=ep target/release/energibridge;
      - run: energibridge
