name: run-energy-measurer

on:
  pull_request:
    types: [opened, reopened]
jobs:
  measure-energy:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: A job to measure energy
    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        
      - name: run-energy-measuring
        id: energy
        uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          what-to-test: sleep 60
