name: run-energy-measurer

on:
#  pull_request:
#    types: [opened, reopened, synchronize]
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - .github/**
jobs:
  measure-energy:
    runs-on: ubuntu-latest
    permissions: write-all
#      contents: read
#      pull-requests: write
    name: A job to measure energy
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - run: echo "PR is ${{ steps.PR.outputs }}"
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        
      - name: run-energy-measuring
        id: energy
        uses: ./
        with:
          run: sleep 5
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
