name: run-code

on:
  push:
    branches:
      - main
jobs:
  measure-energy:
    runs-on: ubuntu-latest
    name: A job to measure energy
    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        
      - name: run-energy-measuring
        id: hello
        uses: ./
        with:
          what-to-test: sleep 60
