name: run-energy-measurer

on:
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - .github/**
      - .energy/**
jobs:
  measure-energy:
    runs-on: ubuntu-latest
    permissions: write-all
    name: A job to measure energy
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: run-energy-measuring
        id: energy
        uses: ./
        with:
          run: sleep 8
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}