name: run-code

on:
  push:
    branches:
      - main
jobs:
  measure-energy:
    runs-on: ubuntu-latest
    name: A job to measure energy
    steps:
      - name: run-energy-measuring
        id: hello
        uses: koenhagen/measure-energy-action@v0.2
        with:
          what-to-test: sleep 60
          
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
