name: run-energy-measurer

on:
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - .github/**
      - .energy/**
  pull_request:
    types:
      - opened
      - reopened
jobs:
  measure-energy:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Measure energy
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: run-energy-measuring
        id: energy
        uses: ./
        with:
          run: sleep 10
          count: 5
          historic: 2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}