name: run-energy-measurer

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
jobs:
  measure-energy:
    runs-on: ubuntu-latest
    permissions: write-all
#      contents: read
#      pull-requests: write
    name: A job to measure energy
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        
      - name: run-energy-measuring
        id: energy
        uses: ./
        with:
          what-to-test: sleep 5
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
