name: run-energy-measurer

on: [push, pull_request]
jobs:
  measure-energy:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Measure energy
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: run-energy-measuring
        id: energy
        uses: ./
        with:
          run: sleep 10
          count: 5
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}